[[repos]]
repo = "local"
hooks = [
  {
    id = "cargo-fmt",
    name = "cargo fmt",
    language = "system",
    entry = "cargo fmt -- --check",
    pass_filenames = false,
  },
  {
    id = "cargo-clippy",
    name = "cargo clippy",
    language = "system",
    entry = "cargo clippy --all-targets --all-features -- -D warnings",
    pass_filenames = false,
  },
  {
    id = "cargo-test",
    name = "cargo test",
    language = "system",
    entry = "cargo test --all-targets --all-features",
    pass_filenames = false,
  },
]